In [73]:
import pandas as pd
import os

In [74]:
goal_path = "../data/labelled_goals/daily_goal_embeddings.csv"

In [75]:
cols = ["ParticipantIdentifier", "ResultIdentifier", "Answers", "trial_date", "label", "embedding"]
goal_df = pd.read_csv(goal_path)[cols].drop_duplicates(subset=['ParticipantIdentifier', 'ResultIdentifier', 'trial_date'])
goal_df.head()

,ParticipantIdentifier,ResultIdentifier,Answers,trial_date,label,embedding
0,1b9b62f1-095b-4819-92a0-ea8e7abee884,DAILY_goal2_set,Read,2022-10-24,Reading_leisure,"[0.014083514921367168, 0.021316660568118095, -..."
1,6e86c427-c679-4acd-aeb4-19ada9022b66,DAILY_goal2_set,review more c37,2022-10-24,School,"[-0.010716583579778671, 0.03636825829744339, -..."
2,7d501571-5d23-4f09-9266-1644f4f71add,DAILY_goal1_set,Study for psychology midterm,2022-10-24,School,"[0.0011260673636570573, -0.021096592769026756,..."
3,7d501571-5d23-4f09-9266-1644f4f71add,DAILY_goal2_set,Get active more,2022-10-24,Exercise,"[-0.026380401104688644, 0.03562040999531746, -..."
4,8a5a92f3-472a-4a39-bfd8-f43f60fdcd27,DAILY_goal1_set,Psy note,2022-10-24,School,"[0.01974469982087612, -0.0020304976496845484, ..."

In [76]:
goal_wide = goal_df[["ParticipantIdentifier", "ResultIdentifier", "Answers", "trial_date"]].pivot(
    index=['ParticipantIdentifier', 'trial_date'],
    columns=['ResultIdentifier'], 
    values='Answers'
).reset_index()

label_wide = goal_df[["ParticipantIdentifier", "ResultIdentifier", "trial_date", "label"]].pivot(
    index=['ParticipantIdentifier', 'trial_date'],
    columns=['ResultIdentifier'], 
    values='label'
).rename(columns={
    "DAILY_goal1_set": "DAILY_goal1_label",
    "DAILY_goal2_set": "DAILY_goal2_label"
}).reset_index()

embedding_wide = goal_df[["ParticipantIdentifier", "ResultIdentifier", "trial_date","embedding"]].pivot(
    index=['ParticipantIdentifier', 'trial_date'],
    columns=['ResultIdentifier'], 
    values='embedding'
).rename(columns={
    "DAILY_goal1_set": "DAILY_goal1_embedding",
    "DAILY_goal2_set": "DAILY_goal2_embedding"
}).reset_index()

In [77]:
goal_wide.head(3)

ResultIdentifier,ParticipantIdentifier,trial_date,DAILY_goal1_set,DAILY_goal2_set
0,0501ba67-3406-4779-aff1-878a0e9f7885,2022-09-30,"Study history and psychology, practice the violin",Do exercise
1,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-03,review,movie review
2,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-07,practice the violin,Work out

In [78]:
label_wide.head(3)

ResultIdentifier,ParticipantIdentifier,trial_date,DAILY_goal1_label,DAILY_goal2_label
0,0501ba67-3406-4779-aff1-878a0e9f7885,2022-09-30,School,Exercise
1,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-03,School,Culture
2,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-07,Hobby,Exercise

In [79]:
embedding_wide.head(3)

ResultIdentifier,ParticipantIdentifier,trial_date,DAILY_goal1_embedding,DAILY_goal2_embedding
0,0501ba67-3406-4779-aff1-878a0e9f7885,2022-09-30,"[-0.038126230239868164, -0.021308906376361847,...","[-0.012392040342092514, 0.017055129632353783, ..."
1,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-03,"[0.03161436691880226, 0.029465556144714355, -0...","[-0.02972441539168358, 0.03863658756017685, -0..."
2,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-07,"[-0.01599280908703804, -0.0059240879490971565,...","[-0.03653150796890259, 0.02275843359529972, -0..."

In [80]:
goal_wide = goal_wide.merge(label_wide, on=["ParticipantIdentifier", "trial_date"])
goal_wide = goal_wide.merge(embedding_wide, on=["ParticipantIdentifier", "trial_date"])

In [81]:
goal_wide.head(3)

ResultIdentifier,ParticipantIdentifier,trial_date,DAILY_goal1_set,DAILY_goal2_set,DAILY_goal1_label,DAILY_goal2_label,DAILY_goal1_embedding,DAILY_goal2_embedding
0,0501ba67-3406-4779-aff1-878a0e9f7885,2022-09-30,"Study history and psychology, practice the violin",Do exercise,School,Exercise,"[-0.038126230239868164, -0.021308906376361847,...","[-0.012392040342092514, 0.017055129632353783, ..."
1,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-03,review,movie review,School,Culture,"[0.03161436691880226, 0.029465556144714355, -0...","[-0.02972441539168358, 0.03863658756017685, -0..."
2,0501ba67-3406-4779-aff1-878a0e9f7885,2022-10-07,practice the violin,Work out,Hobby,Exercise,"[-0.01599280908703804, -0.0059240879490971565,...","[-0.03653150796890259, 0.02275843359529972, -0..."

In [82]:
goal_wide.to_csv(os.path.join("../data/proc/goals/daily_goals_labeled_embedding_wide.csv"), index=False)